csk/urls.py
from django.urls import path
from csk.views import *
app_name='csk'
urlpatterns=[
    path('msd1/',msd1,name='msd1'),
    path('msd2/',msd2,name='msd2'),

]

rcb/urls.py
from django.urls import path
from rcb.views import *
app_name='rcb'
urlpatterns=[
    path('virat1/',virat1,name='virat1'),
    path('virat2/',virat2,name='virat2'),

]

specific_url_navigation/urls.py
from django.contrib import admin
from django.urls import path,include
import csk,rcb
from india.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('india2/',india2,name='india2'),
    path('csk/',include('csk.urls')),
    path('rcb/',include('rcb.urls')),
    
]

india/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def msd1(request):
    return HttpResponse('This is msd page')
def msd2(request):
    return render(request,'dhoni.html')

india/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def india1(request):
    return HttpResponse('this is india branch page')
def india2(request):
    return render(request,'sachin.html')

rcb/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def virat1(request):
    return HttpResponse('This is virat1 page')
def virat2(request):
    return render(request,'virat.html')

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is dhoni page</h1>
        <h1><a href="{% url 'rcb:virat2' %}">navigate to virat page</a></h1>
    </center>
</body>
</html>

templates/sachin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>india app page</title>
</head>
<body>
    <center>
        <h1>This is sachin page</h1>
        <h1><a href="{% url 'csk:msd2' %}">navigate to dhoni page</a></h1>
        <h1><a href="{% url 'rcb:virat2' %}">navigate to virat page</a></h1>
    </center>
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>virat_ rcb</title>
</head>
<body>
   <center>
    <h1>This is virat page</h1>
    <h1><a href="{% url 'csk:msd2' %}">navigate to dhoni page</a></h1>
    <h1><a href="{% url 'india2' %}">navigate to sachin page</a></h1>
   </center> 
</body>
</html>